In [4]:
import pandas as pd

In [5]:
wine_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
wine_data = pd.read_csv(wine_url, header = None)

In [6]:
wine_data.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185

In [7]:
# Attribution de noms de colonnes significatifs
wine_data.columns = [
    "class",
    "alcohol",
    "malic acid",
    "ash",
    "alcalinité des cendres",
    "magnésium",
    "phénols totaux",
    "flavonoïdes",
    "phénols non flavonoïdes",
    "proanthocyanidines",
    "intensité de la couleur",
    "teinte",
    "DO280/DO315 des vins dilués",
    "proline",
]

In [8]:
wine_data.head(3)

,class,alcohol,malic acid,ash,alcalinité des cendres,magnésium,phénols totaux,flavonoïdes,phénols non flavonoïdes,proanthocyanidines,intensité de la couleur,teinte,DO280/DO315 des vins dilués,proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185

In [9]:
wine_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   class                        178 non-null    int64
 1   alcohol                      178 non-null    float64
 2   malic acid                   178 non-null    float64
 3   ash                          178 non-null    float64
 4   alcalinité des cendres       178 non-null    float64
 5   magnésium                    178 non-null    int64
 6   phénols totaux               178 non-null    float64
 7   flavonoïdes                  178 non-null    float64
 8   phénols non flavonoïdes      178 non-null    float64
 9   proanthocyanidines           178 non-null    float64
 10  intensité de la couleur      178 non-null    float64
 11  teinte                       178 non-null    float64
 12  DO280/DO315 des vins dilués  178 non-null    float64
 13  proline                      178 non-null    int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB

In [10]:
wine_data.duplicated().sum()

np.int64(0)

In [11]:
wine_data.isnull().sum()

class                          0
alcohol                        0
malic acid                     0
ash                            0
alcalinité des cendres         0
magnésium                      0
phénols totaux                 0
flavonoïdes                    0
phénols non flavonoïdes        0
proanthocyanidines             0
intensité de la couleur        0
teinte                         0
DO280/DO315 des vins dilués    0
proline                        0
dtype: int64

In [12]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

engine = create_engine(DATABASE_URL)

with engine.connect() as conn:
    print("Connexion réussie !")

Connexion réussie !

In [13]:
wine_data.to_sql(
    "wine",
    engine,
    if_exists="replace",
    index=False
)

178

In [14]:
import pandas as pd

df_check = pd.read_sql(
    "SELECT * FROM wine LIMIT 5",
    engine
)

df_check

,class,alcohol,malic acid,ash,alcalinité des cendres,magnésium,phénols totaux,flavonoïdes,phénols non flavonoïdes,proanthocyanidines,intensité de la couleur,teinte,DO280/DO315 des vins dilués,proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [15]:
from Transformation.data_cleaning import transform_data

In [16]:
wine_clean, report = transform_data(wine_data)

In [17]:
wine_clean.head()

,class,alcohol,malic_acid,ash,alcalinit_des_cendres,magn_sium,ph_nols_totaux,flavono_des,ph_nols_non_flavono_des,proanthocyanidines,intensit_de_la_couleur,teinte,do280_do315_des_vins_dilu_s,proline,alcohol_malic_ratio
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,8.321637
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,7.415730
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,5.576271
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,7.369231
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,5.111969

In [18]:
report

{'missing_values': class                          0
 alcohol                        0
 malic acid                     0
 ash                            0
 alcalinité des cendres         0
 magnésium                      0
 phénols totaux                 0
 flavonoïdes                    0
 phénols non flavonoïdes        0
 proanthocyanidines             0
 intensité de la couleur        0
 teinte                         0
 DO280/DO315 des vins dilués    0
 proline                        0
 dtype: int64,
 'duplicates_removed': np.int64(0),
 'column_mapping': {'class': 'class',
  'alcohol': 'alcohol',
  'malic acid': 'malic_acid',
  'ash': 'ash',
  'alcalinité des cendres': 'alcalinit_des_cendres',
  'magnésium': 'magn_sium',
  'phénols totaux': 'ph_nols_totaux',
  'flavonoïdes': 'flavono_des',
  'phénols non flavonoïdes': 'ph_nols_non_flavono_des',
  'proanthocyanidines': 'proanthocyanidines',
  'intensité de la couleur': 'intensit_de_la_couleur',
  'teinte': 'teinte',
  'DO280/DO315 des vins dilués': 'do280_do315_des_vins_dilu_s',
  'proline': 'proline'}}

In [19]:
with open("Anomalie/methode_z_score.py", "r") as f:
    print(f.read())

import pandas as pd
import numpy as np
from scipy.stats import zscore


def detect_anomalies_zscore(
    df: pd.DataFrame,
    columns: list,
    threshold: float = 3
):
    df_copy = df.copy()

    z_scores = np.abs(
        zscore(df_copy[columns])
    )

    df_copy["anomalie_zscore"] = (
        z_scores > threshold
    ).any(axis=1)

    return df_copy

In [20]:
from Anomalie.methode_z_score import *

In [21]:
import importlib
import Anomalie

importlib.reload(Anomalie)

In [22]:
import Anomalie.methode_z_score as mz

print(dir(mz))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'detect_anomalies_zscore', 'np', 'pd', 'zscore']

In [25]:
from Anomalie.methode_z_score import detect_anomalies_zscore

In [33]:
from Anomalie.methode_isolation_forest import detect_anomalies_isolation_forest

In [28]:
from Anomalie import detect_anomalies_zscore

In [31]:
print(wine_data.columns)

Index(['class', 'alcohol', 'malic acid', 'ash', 'alcalinité des cendres',
       'magnésium', 'phénols totaux', 'flavonoïdes', 'phénols non flavonoïdes',
       'proanthocyanidines', 'intensité de la couleur', 'teinte',
       'DO280/DO315 des vins dilués', 'proline'],
      dtype='str')

In [34]:
df_y = detect_anomalies_isolation_forest(
    wine_data,
    columns=["alcohol", "magnésium"]
)

df_y.head()

,class,alcohol,malic acid,ash,alcalinité des cendres,magnésium,phénols totaux,flavonoïdes,phénols non flavonoïdes,proanthocyanidines,intensité de la couleur,teinte,DO280/DO315 des vins dilués,proline,anomalie_iforest
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,False
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,False
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,False
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,False
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,False

In [35]:
df_z = detect_anomalies_zscore(
    wine_data,
    columns=["alcohol", "magnésium"]
)

df_z.head()

,class,alcohol,malic acid,ash,alcalinité des cendres,magnésium,phénols totaux,flavonoïdes,phénols non flavonoïdes,proanthocyanidines,intensité de la couleur,teinte,DO280/DO315 des vins dilués,proline,anomalie_zscore
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,False
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,False
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,False
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,False
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,False

In [ ]:
from Extaction.charger_base_de_donnee import load

In [ ]:
val = load(wine_url)
val.head(5)

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450

In [ ]:
from Extaction.fonction_global_extract import load_data

In [ ]:
val1 = load_data(wine_url)
val1.head(5)

,1,14.23,1.71,2.43,15.6,127,2.8,3.06,.28,2.29,5.64,1.04,3.92,1065
0,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
1,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
2,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
3,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
4,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450